pipeline {
    agent any {
        stages{
            stage("build"){
                steps{
                    echo "buildind...."
                    sh "docker images"
                }
            }
        }
    }
    
